# check working example at 20250107 on git
from snakemake.utils import min_version
min_version("8.0")
import pandas as pd

configfile: "config/config.yaml"

# input data
samples = pd.read_csv(config["sample_metadata"])["study_index"].tolist()

rule all:
    input:
        expand("results/plot/{sample}.png", sample=samples)

rule generate_data:
    params:
        seed=config["generate_data"]["seed"]
    output:
        output="data/{sample}.csv"
    script: 
        "scripts/generate_data.R" 

rule wrangle:
    input:
        input="data/{sample}.csv"
    params:
        nrow=config["wrangle"]["nrow"]
    output:
        output="results/wrangled/{sample}.csv"
    script: 
        "scripts/wrangle.R" 

rule plot:
    input:
        input="results/wrangled/{sample}.csv"
    params:
        color=config["plot"]["color"]
    output:
        output="results/plot/{sample}.png"
    script: 
        "scripts/plot.R" 
