# check working example at 20250107 on git
from snakemake.utils import min_version
min_version("8.0")
import pandas as pd

configfile: "config/config.yaml"

# input data
samples = pd.read_csv(config["sample_metadata"])["study_index"].tolist()

rule all:
    input:
        expand("data/{sample}.csv", sample=samples)

rule generate_data:
	params:
		seed=config["generate_data"]["seed"]
	output:
		output="data/{sample}.csv"
	shell:
		"""
		Rscript workflow/scripts/generate_data.R \
		--sample {wildcards.sample} \
		--seed {params.seed} \
		--output {output.output}
		"""